config/routes.rb
Rails.application.routes.draw do
  
  resources :employees


  resources :emptests do 
  	collection { post :import }
  end

  devise_for :logins, :controllers=>{ :registrations => "registrations"}

 
  resources :testemps do
    collection { post :upload }
  end

  #root 'testemps#index'
  #root 'emptests#index'

  root 'welcomes#index'
  get 'dateselect', to: 'attendances#dateselect'


  #root 'attendances#index'

  #get '/login' => redirect('/logins/sign_in')

  #get 'emptests', to: 'emptests#index'

    #root "admins#index"
  

  #resources :admins do
   # collection { post :import }
  #end

 resources :attendances do
    collection { post :upload }
    collection { post :dateselect }
  end
  

  
  
end

app/models/testemp.rb
class Testemp < ActiveRecord::Base

	def self.to_csv(options = {})
	    CSV.generate(options) do |csv|
	      csv << column_names
	      all.each do |rec|
	        csv << rec.attributes.values_at(*column_names)
	      end
	    end
	  end

end

app/controllers/testemps_controller.rb
class TestempsController < ApplicationController

	

  def index
    
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end



  def upload
    @records = []
    records = params[:file].path
    @records = CSV.foreach(records, headers:true)
  end

end

app/helpers/testemps_helper.rb
module TestempsHelper
end

app/views/testemps/index.html.erb
<h1>Admin Page</h1>

<h3>Welcome Admin</h3>

  <%= form_tag upload_testemps_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag 'Upload File', class:"form-button" %>
  <% end %>

app/views/testemps/upload.html.erb
<h1>All Employee Records</h1>

<table align="center">
  <% @records.each do |rec|%>
    <tr>
      <td><%= rec[0] %></td>
      <td><%= rec[1] %></td>
      <td><%= rec[2] %></td>
      <td><%= rec[3] %></td>
      <td><%= rec[4] %></td>
      <td><%= rec[5] %></td>
      <td><%= rec[6] %></td>
      <td><%= rec[7] %></td>
      <td><%= rec[8] %></td>
      <td><%= rec[9] %></td>
      <td><%= rec[10] %></td>
      <td><%= rec[11] %></td>
      <td><%= rec[12] %></td>
      <td><%= rec[13] %></td>

    </tr>
  <% end %>
</table>



<button class="form-button"><%= link_to "Back", testemps_path %>