config/routes.rb
Rails.application.routes.draw do
  
  resources :employees


  resources :emptests do 
  	collection { post :import }
  end

  devise_for :logins, :controllers=>{ :registrations => "registrations"}

 
  resources :testemps do
    collection { post :upload }
  end

  #root 'testemps#index'
  #root 'emptests#index'

  root 'welcomes#index'
  get 'dateselect', to: 'attendances#dateselect'


  #root 'attendances#index'

  #get '/login' => redirect('/logins/sign_in')

  #get 'emptests', to: 'emptests#index'

    #root "admins#index"
  

  #resources :admins do
   # collection { post :import }
  #end

 resources :attendances do
    collection { post :upload }
    collection { post :dateselect }
  end
  

  
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	has_many :attendances
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_emp, only: [:show, :edit, :update, :destroy]


  def index
    @employees = Employee .all
  end
  
  def new
    @employee = Employee.new
  end

  def show
  end

  def edit
  end

  def create
      @employee = Employee.create(emp_params)
      if @employee.save
          redirect_to @employee, notice: 'Employee was successfully created.'
      else
        render action: "new"
      end
  end

  def destroy
    @employee.destroy
    redirect_to attendances_path
  end

  def update
      if @employee.update(emp_params)
        redirect_to @employee
      else
        render action: 'edit'
      end
  end 

  private
    def set_emp
      @employee = Employee.find(params[:id])
    end

    def emp_params
      params.require(:employee).permit(:name)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
    
    <div class= "form-group" >
        <b> <%= f.label :name, :class => "labelbox" %> </b> 
        <%= f.text_field :name, :class => "textbox" %>
    </div>

    <br>
    <br>  
        <%= f.submit :class => 'all-button'%>
   <% end %>

app/views/employees/edit.html.erb
<h1> Editing Employee </h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> 

<%= link_to 'ok', attendances_path %>

app/views/employees/index.html.erb
<h1> Listing Employee </h1>

<table border="1">
  <tr>
    <th> Id</th>
    <th> Name </th>
    
  </tr>

  <% @employees.each do |emp| %>
  <tr>
    <td> <%= emp.id %> </td>
    <td> <%= emp.name %> </td>
   
    <td> <%= link_to 'Show', emp %> </td>
    <td> <%= link_to 'Edit', edit_employee_path(emp) %> </td>
    <td> <%= link_to 'Destroy', emp, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
  </tr>
  <% end %>
</table>

<br />

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Cancel', attendances_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= @employee.name %> 

<%= link_to 'Edit', edit_employee_path(@employee) %> | 
<%= link_to 'Exit', attendances_path %>