config/routes.rb
Rails.application.routes.draw do
  
  resources :employees


  resources :emptests do 
  	collection { post :import }
  end

  devise_for :logins, :controllers=>{ :registrations => "registrations"}

 
  resources :testemps do
    collection { post :upload }
  end

  #root 'testemps#index'
  #root 'emptests#index'

  root 'welcomes#index'
  get 'dateselect', to: 'attendances#dateselect'


  #root 'attendances#index'

  #get '/login' => redirect('/logins/sign_in')

  #get 'emptests', to: 'emptests#index'

    #root "admins#index"
  

  #resources :admins do
   # collection { post :import }
  #end

 resources :attendances do
    collection { post :upload }
    collection { post :dateselect }
  end
  

  
  
end

app/models/emptest.rb
class Emptest < ActiveRecord::Base
	


	def self.import(file)
		CSV.foreach(file.path, headers: true) do |row|
			Emptest.create! row.to_hash
		end
	end
end

app/controllers/emptests_controller.rb
class EmptestsController < ApplicationController
  before_action :set_emptest, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @emptests = Emptest.all
    respond_with(@emptests)
  end

  def show
    respond_with(@emptest)
  end

  def new
    @emptest = Emptest.new
    respond_with(@emptest)
  end

  def edit
  end

  def create
    @emptest = Emptest.new(emptest_params)
    @emptest.save
    respond_with(@emptest)
  end

  def update
    @emptest.update(emptest_params)
    respond_with(@emptest)
  end

  def destroy
    @emptest.destroy
    respond_with(@emptest)
  end

  def import
    begin
        Emptest.import(params[:file])
            redirect_to emptests_path, notice: "Data uploaded successfully"
    rescue
          redirect_to emptests_path, notice: "Invalid CSV file format."
      end
  end



  private
    def set_emptest
      @emptest = Emptest.find(params[:id])
    end

    def emptest_params
      params.require(:emptest).permit(:ecode, :name, :shift, :sintime, :aintime)
    end
end

app/helpers/emptests_helper.rb
module EmptestsHelper
end

app/views/emptests/_form.html.erb
<%= form_for(@emptest) do |f| %>
  <% if @emptest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emptest.errors.count, "error") %> prohibited this emptest from being saved:</h2>

      <ul>
      <% @emptest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ecode %><br>
    <%= f.number_field :ecode %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :shift %><br>
    <%= f.text_field :shift %>
  </div>
  <div class="field">
    <%= f.label :sintime %><br>
    <%= f.time_select :sintime %>
  </div>
  <div class="field">
    <%= f.label :aintime %><br>
    <%= f.time_select :aintime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emptests/edit.html.erb
<h1>Editing emptest</h1>

<%= render 'form' %>

<%= link_to 'Show', @emptest %> |
<%= link_to 'Back', emptests_path %>

app/views/emptests/index.html.erb
<h1>Listing emptests</h1>

<table>
  <thead>
    <tr>
      <th>Ecode</th>
      <th>Name</th>
      <th>Shift</th>
      <th>Sintime</th>
      <th>Aintime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emptests.each do |emptest| %>
      <tr>
        <td><%= emptest.ecode %></td>
        <td><%= emptest.name %></td>
        <td><%= emptest.shift %></td>
        <td><%= emptest.sintime %></td>
        <td><%= emptest.aintime %></td>
        <td><%= link_to 'Show', emptest %></td>
        <td><%= link_to 'Edit', edit_emptest_path(emptest) %></td>
        <td><%= link_to 'Destroy', emptest, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h3> Upload attendance </h3>

<%= form_tag import_emptests_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Upload Attendance" %>
<% end %>

<%= link_to 'New Emptest', new_emptest_path %>

app/views/emptests/new.html.erb
<h1>New emptest</h1>

<%= render 'form' %>

<%= link_to 'Back', emptests_path %>

app/views/emptests/show.html.erb
<p id="notice"><%= notice %></p>

<table border="1">
  <thead>
    <tr>
      <th>Ecode</th>
      <th>Name</th>
      <th>Shift</th>
      <th>Sintime</th>
      <th>Aintime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  
      <tr>
        <td><%= @emptest.ecode %></td>
        <td><%= @emptest.name %></td>
        <td><%= @emptest.shift %></td>
        <td><%= @emptest.sintime %></td>
        <td><%= @emptest.aintime %></td>
      </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_emptest_path(@emptest) %> |
<%= link_to 'Back', emptests_path %>