config/routes.rb
Rails.application.routes.draw do
  
  resources :employees


  resources :emptests do 
  	collection { post :import }
  end

  devise_for :logins, :controllers=>{ :registrations => "registrations"}

 
  resources :testemps do
    collection { post :upload }
  end

  #root 'testemps#index'
  #root 'emptests#index'

  root 'welcomes#index'
  get 'dateselect', to: 'attendances#dateselect'


  #root 'attendances#index'

  #get '/login' => redirect('/logins/sign_in')

  #get 'emptests', to: 'emptests#index'

    #root "admins#index"
  

  #resources :admins do
   # collection { post :import }
  #end

 resources :attendances do
    collection { post :upload }
    collection { post :dateselect }
  end
  

  
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AttendanceMonitoring</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <link href='http://fonts.googleapis.com/css?family=Amaranth:700,700italic,400italic,400' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag('default', :media => :screen) %>
  <%= stylesheet_link_tag('print', :media => :print) %>

</head>
<body>  
  <div class = "container">
    <h1 class = 'fixed'> Mahaswami Software Pvt Ltd </h1>
      <% if login_signed_in? %>
        
        <button class= "all-button" > <%= link_to destroy_login_session_path, method: :delete do %>
        <i class="fa fa-power-off fa-1x"></i> <% end %> </button>

        <p id = "username"> <b> <i class="fa fa-user fa-2x"></i> </b> <%= link_to current_login.email, edit_login_registration_path %> </p>
      <% else %>
          <% unless current_page?(root_path) %>
                <button class= "all-button" > <%= link_to "Loginhome",root_path %>  </button>
           <% end %>

        <% end %>
    </div>          
 
<div class = "wrapper1">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  </div>

<header class = "wrappers" class = "clearfix">

<div class = "wrapper">
	<%= yield %>
</div>


</header>




</body>
</html>